In [1]:
import numpy as np

In [6]:
np.random.seed(32)

a1 = np.random.randint(1,20, 8)
print(a1)

[12  6  8  4  6 11 10  5]


In [7]:
a2 = np.random.randint(1,100, 8)
print(a2)

[12 82  4 66 35 36 25 43]


In [8]:
a1 + a2

array([24, 88, 12, 70, 41, 47, 35, 48])

In [9]:
#para a soma acima dar certo, é necessario que tanto o a1 quanto o a2 tenham a mesma quantidade de elementos/casas

In [10]:
m1 = np.random.randint(1,10, (3,2))
print(m1)

[[3 5]
 [3 5]
 [5 6]]


In [11]:
m2 = np.random.randint(1, 10, (2,3))
print(m2)

[[7 9 5]
 [1 7 5]]


In [12]:
m1.dot(m2)

array([[26, 62, 40],
       [26, 62, 40],
       [41, 87, 55]])

In [15]:
m1 = np.ones((3,2))
m2 = np.ones((2,3))
print(m1)
print(m2)
m1.dot(m2)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]]


array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

Comparações

In [16]:
a1 = np.array([1,2,3,1])
a2 = np.array([2,2,3,1])

np.array_equal(a1, a2)

False

In [17]:
a1 = np.array([1,2,3,1])
a2 = np.array([1,2,3,1])

np.array_equal(a1, a2)

True

In [18]:
np.sin(a1)

array([0.84147098, 0.90929743, 0.14112001, 0.84147098])

In [19]:
np.sum(a1)

7

In [20]:
np.var(a1)

0.6875

In [21]:
#desvio padrao
np.std(a1)

0.82915619758885