In [1]:
import numpy as np

In [2]:
a = np.random.randn(10)
print(a)

[ 1.25938368 -0.69807748  0.68691925  1.49533546 -0.13679175  0.0390435
  1.03095249  0.5780042   1.72956662  0.49022556]


In [3]:
b = np.random.randn(3,3)
print(b)

[[ 0.16639106  1.19701317  1.01667944]
 [ 1.7590775   0.55943764 -0.74515395]
 [-2.17900357 -0.45072767  0.03857024]]


In [4]:
a.ndim

1

In [5]:
b.ndim

2

In [6]:
a.dtype

dtype('float64')

In [7]:
a.astype('int')

array([1, 0, 0, 1, 0, 0, 1, 0, 1, 0])

In [8]:
a.max()

1.7295666172858297

In [9]:
a.min()

-0.6980774836065773

In [10]:
#posição do indice que se encontra o maior valor
a.argmax()

8

In [12]:
#posição do indice que se encontra o menor valor
a.argmin()

1

In [13]:
a.sum()

6.474561512480712

In [14]:
a.mean()

0.6474561512480712

In [15]:
a.var()

0.5238160973676383

In [16]:
a.std()

0.7237514057793866

In [17]:
a

array([ 1.25938368, -0.69807748,  0.68691925,  1.49533546, -0.13679175,
        0.0390435 ,  1.03095249,  0.5780042 ,  1.72956662,  0.49022556])

In [18]:
a.sort()

In [19]:
a

array([-0.69807748, -0.13679175,  0.0390435 ,  0.49022556,  0.5780042 ,
        0.68691925,  1.03095249,  1.25938368,  1.49533546,  1.72956662])

In [20]:
#transpor é com letra T maiuscula
b

array([[ 0.16639106,  1.19701317,  1.01667944],
       [ 1.7590775 ,  0.55943764, -0.74515395],
       [-2.17900357, -0.45072767,  0.03857024]])

In [21]:
b.T

array([[ 0.16639106,  1.7590775 , -2.17900357],
       [ 1.19701317,  0.55943764, -0.45072767],
       [ 1.01667944, -0.74515395,  0.03857024]])

Máscara

In [27]:
a = np.array([1, 2, 3, 4])

In [29]:
a[[False, True, False, True]]#isso aqui é a máscara

array([2, 4])

In [30]:
a >= 3

array([False, False,  True,  True])

In [31]:
a[a>=3]

array([3, 4])

In [32]:
a[a % 2 == 0]

array([2, 4])

In [34]:
a % 2 == 0 #máscara tbem

array([False,  True, False,  True])

In [35]:
a>=3

array([False, False,  True,  True])