In [1]:
import numpy as np

In [2]:
a = np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [3]:
print(a)

[0 1 2 3]


In [4]:
print(type(a))

<class 'numpy.ndarray'>


In [8]:
#se fizer sem o segundo colchete dá erro
b = np.array([[0,1,2], [3,4,5]])
print(b)
print(b.ndim)
#primeira dimensão = linhas
#segunda dimensão = colunas

[[0 1 2]
 [3 4 5]]
2


In [11]:
print(b.shape)

(2, 3)


In [12]:
print(len(b))
#retorna apenas o número da primeira dimensão, no caso, linhas

2


Criando Utilização de funções pelo NP

In [14]:
#similar ao range do python (for)
c = np.arange(0,91,1)

print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90]


In [19]:
#o linspace, pode ser entendido como, o ponto inicial, o ponto final e, o último, a quantidade de elementos entre existente entre o inicial e o final
#nessa abordagem, o inicial e final, também entram na contagem da quantidade de elementos.
#ainda pode existir uma quarta casa: "endpoint=False", que excluirá o ponto final, igual o arangue e o range.
d = np.linspace(1,10,6)
print(d)

[ 1.   2.8  4.6  6.4  8.2 10. ]


Arrays comuns

In [24]:
#array de 1, é preciso indicar dentro dos parênteses a qutde
e = np.ones(10)
print(e)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [26]:
#criando uma array bidimensional
f = np.ones((2,3))

print(f)

[[1. 1. 1.]
 [1. 1. 1.]]


In [32]:
#o "ones", pode ser substituido por zero, segue o exemplo:
g = np.zeros(10)
print(g)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [36]:
#matriz de números aleatórios

h = np.random.rand(4) #acessando o random, uma das funções ali é o rand, que escolherá números entre 0 e 1
print(h)
#aqui tbem, não precisa colocar um segundo parênteses tipo shape

[0.58815763 0.96104378 0.95319147 0.96799998]


In [39]:
#matriz diagonal pela expressao eye
i = np.eye(3) #o numero dentro dos parênteses indica a qtde de numeros 1 na diagonal
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [40]:
j = np.diag(np.array([1,2,3,4]))
print(j)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


Exercícios

In [46]:
#Criar uma matriz identidade com dimensão 5 x 5:
#matriz identidade é quando a diagonal são todas iguais a 1

In [47]:
identidade = np.eye(5)
print(identidade)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [48]:
#Crie uma matriz 3 x 3 com todos os elementos iguais a 1

In [49]:
iguais = np.ones((3,3))
print(iguais)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [43]:
#crie uma matriz 2 x 3 com elementos de valores aleatórios entre 0 a 20

In [58]:
#a primeira casa vem o limite de 20, e o bidimensional vem por meio do size.
aleatorio = np.random.randint(20, size=(2,3))
print(aleatorio)

[[ 0 14 12]
 [ 3  6 13]]


In [44]:
#crie um vetor :[9,8,7,6,5,4,3,2,1]

In [61]:
inverso = np.arange(9, 0, -1)
print(inverso)

[9 8 7 6 5 4 3 2 1]


Fim dos primeiros exercícios

# Indexação e cortes (Slices) de arrays

In [68]:
aa = np.arange(10,20)
print(aa)
print('Acessando um elemento dentro da lista aa')
aa[1]

[10 11 12 13 14 15 16 17 18 19]
Acessando um elemento dentro da lista aa


11

In [73]:
bb = np.random.rand(5,5)

print(bb)
print(30*'-=')
print('Com bb[0], vai puxar a primeira linha inteira')
bb[0]# pelo shape, o np identifica apenas linha e coluna, assim, quando digitado a linha sem especificar a coluna, a resposta será a linha inteira.
print(30*'-=')
print('incluindo o número depois da virgula, está especificando qual coluna será retirada o valor da linha [0,3]')
bb[0,3]

[[0.99536488 0.34174416 0.17893583 0.88016232 0.309799  ]
 [0.16043152 0.76095812 0.1929859  0.32593654 0.99534443]
 [0.86936601 0.67790554 0.48632583 0.65357447 0.4817373 ]
 [0.74591124 0.08454993 0.2865407  0.30289044 0.22837966]
 [0.61856564 0.10935669 0.97189463 0.5734396  0.47651897]]
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Com bb[0], vai puxar a primeira linha inteira
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
incluindo o número depois da virgula, está especificando qual coluna será retirada o valor da linha [0,3]


0.8801623154927809

In [78]:
#alterando um valor
print(bb)
bb[0,1] = 2

[[0.99536488 0.34174416 0.17893583 0.88016232 0.309799  ]
 [0.16043152 0.76095812 0.1929859  0.32593654 0.99534443]
 [0.86936601 0.67790554 0.48632583 0.65357447 0.4817373 ]
 [0.74591124 0.08454993 0.2865407  0.30289044 0.22837966]
 [0.61856564 0.10935669 0.97189463 0.5734396  0.47651897]]


In [80]:
#o valor da linha 0, coluna 1
print(bb)

[[0.99536488 2.         0.17893583 0.88016232 0.309799  ]
 [0.16043152 0.76095812 0.1929859  0.32593654 0.99534443]
 [0.86936601 0.67790554 0.48632583 0.65357447 0.4817373 ]
 [0.74591124 0.08454993 0.2865407  0.30289044 0.22837966]
 [0.61856564 0.10935669 0.97189463 0.5734396  0.47651897]]


In [83]:
#unidimensional
print(aa)

[10 11 12 13 14 15 16 17 18 19]


In [84]:
#slices de um vetor unidimensional
print(aa[2:5])

[12 13 14]


In [85]:
print(bb)

[[0.99536488 2.         0.17893583 0.88016232 0.309799  ]
 [0.16043152 0.76095812 0.1929859  0.32593654 0.99534443]
 [0.86936601 0.67790554 0.48632583 0.65357447 0.4817373 ]
 [0.74591124 0.08454993 0.2865407  0.30289044 0.22837966]
 [0.61856564 0.10935669 0.97189463 0.5734396  0.47651897]]


In [86]:
#slices de linhas
print(bb[0:2])

[[0.99536488 2.         0.17893583 0.88016232 0.309799  ]
 [0.16043152 0.76095812 0.1929859  0.32593654 0.99534443]]


In [89]:
#cortando as linhas com colunas, para tanto, depois de ter cortado as linhas, basta inserir uma vírgula, que após ela, estará fazendo referencia a colunas

print(bb[0:2, 2])

[0.17893583 0.1929859 ]
